Update ptero-install

diff --git a/ptero-install b/ptero-install
--- a/ptero-install
+++ b/ptero-install
@@ -1,114 +1,117 @@
-!/bin/bash
+#!/bin/bash
 
-set -e
+# ===============================
+# DracoHost Animated Installer
+# ===============================
 
-######################################################################################
-#                                                                                    #
-# Project 'pterodactyl-installer'                                                    #
-#                                                                                    #
-# Copyright (C) 2018 - 2025, Vilhelm Prytz, <vilhelm@prytznet.se>                    #
-#                                                                                    #
-#   This program is free software: you can redistribute it and/or modify             #
-#   it under the terms of the GNU General Public License as published by             #
-#   the Free Software Foundation, either version 3 of the License, or                #
-#   (at your option) any later version.                                              #
-#                                                                                    #
-#   This program is distributed in the hope that it will be useful,                  #
-#   but WITHOUT ANY WARRANTY; without even the implied warranty of                   #
-#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    #
-#   GNU General Public License for more details.                                     #
-#                                                                                    #
-#   You should have received a copy of the GNU General Public License                #
-#   along with this program.  If not, see <https://www.gnu.org/licenses/>.           #
-#                                                                                    #
-# https://github.com/pterodactyl-installer/pterodactyl-installer/blob/master/LICENSE #
-#                                                                                    #
-# This script is not associated with the official Pterodactyl Project.               #
-# https://github.com/pterodactyl-installer/pterodactyl-installer                     #
-#                                                                                    #
-######################################################################################
-
-export GITHUB_SOURCE="v1.2.0"
-export SCRIPT_RELEASE="v1.2.0"
-export GITHUB_BASE_URL="https://raw.githubusercontent.com/pterodactyl-installer/pterodactyl-installer"
-
-LOG_PATH="/var/log/pterodactyl-installer.log"
-
-# check for curl
-if ! [ -x "$(command -v curl)" ]; then
-  echo "* curl is required in order for this script to work."
-  echo "* install using apt (Debian and derivatives) or yum/dnf (CentOS)"
-  exit 1
-fi
-
-# Always remove lib.sh, before downloading it
-[ -f /tmp/lib.sh ] && rm -rf /tmp/lib.sh
-curl -sSL -o /tmp/lib.sh "$GITHUB_BASE_URL"/master/lib/lib.sh
-# shellcheck source=lib/lib.sh
-source /tmp/lib.sh
-
-execute() {
-  echo -e "\n\n* pterodactyl-installer $(date) \n\n" >>$LOG_PATH
-
-  [[ "$1" == *"canary"* ]] && export GITHUB_SOURCE="master" && export SCRIPT_RELEASE="canary"
-  update_lib_source
-  run_ui "${1//_canary/}" |& tee -a $LOG_PATH
-
-  if [[ -n $2 ]]; then
-    echo -e -n "* Installation of $1 completed. Do you want to proceed to $2 installation? (y/N): "
-    read -r CONFIRM
-    if [[ "$CONFIRM" =~ [Yy] ]]; then
-      execute "$2"
-    else
-      error "Installation of $2 aborted."
-      exit 1
-    fi
-  fi
+# ASCII Logo
+function ascii_logo() {
+    logo="
+|  \\/  |  / \\  |_ _| \\ | |  |  \\/  | ____| \\ | | | | |
+| |\\/| | / _ \\  | ||  \\| |  | |\\/| |  _| |  \\| | | | |
+| |  | |/ ___ \\ | || |\\  |  | |  | | |___| |\\  | |_| |
+|_|  |_/_/   \\_\\___|_| \\_|  |_|  |_|_____|_| \\_|\\___/
+"
+    echo "$logo"
 }
 
-welcome ""
+# Animated Header
+function animate_header() {
+    header="*** DracoHost Panel Light ***"
+    for ((i=0;i<${#header};i++)); do
+        echo -n "${header:$i:1}"
+        sleep 0.05
+    done
+    echo
+}
 
-done=false
-while [ "$done" == false ]; do
-  options=(
-    "Install the panel"
-    "Install Wings"
-    "Install both [0] and [1] on the same machine (wings script runs after panel)"
-    # "Uninstall panel or wings\n"
+# Animated Footer
+function animate_footer() {
+    footer="Pterodactyl install by clowner.py"
+    for ((i=0;i<${#footer};i++)); do
+        echo -n "${footer:$i:1}"
+        sleep 0.03
+    done
+    echo
+}
 
-    "Install panel with canary version of the script (the versions that lives in master, may be broken!)"
-    "Install Wings with canary version of the script (the versions that lives in master, may be broken!)"
-    "Install both [3] and [4] on the same machine (wings script runs after panel)"
-    "Uninstall panel or wings with canary version of the script (the versions that lives in master, may be broken!)"
-  )
+# Loading animation
+function loading_animation() {
+    echo -n "Processing"
+    for i in {1..5}; do
+        echo -n "."
+        sleep 0.4
+    done
+    echo
+}
 
-  actions=(
-    "panel"
-    "wings"
-    "panel;wings"
-    # "uninstall"
+# Banner function
+function show_banner() {
+    clear
+    ascii_logo
+    animate_header
+    echo "======================================"
+}
 
-    "panel_canary"
-    "wings_canary"
-    "panel_canary;wings_canary"
-    "uninstall_canary"
-  )
+# Main Menu
+while true; do
+    show_banner
+    echo "1) Install Pterodactyl Panel"
+    echo "2) Install Pterodactyl Wings"
+    echo "3) Install Cloudflare"
+    echo "4) Install Nebula Theme"
+    echo "0) Exit"
+    echo "======================================"
+    animate_footer
+    echo
+    read -p "Enter your choice [0-4]: " choice
 
-  output "What would you like to do?"
-
-  for i in "${!options[@]}"; do
-    output "[$i] ${options[$i]}"
-  done
-
-  echo -n "* Input 0-$((${#actions[@]} - 1)): "
-  read -r action
-
-  [ -z "$action" ] && error "Input is required" && continue
-
-  valid_input=("$(for ((i = 0; i <= ${#actions[@]} - 1; i += 1)); do echo "${i}"; done)")
-  [[ ! " ${valid_input[*]} " =~ ${action} ]] && error "Invalid option"
-  [[ " ${valid_input[*]} " =~ ${action} ]] && done=true && IFS=";" read -r i1 i2 <<<"${actions[$action]}" && execute "$i1" "$i2"
+    case $choice in
+        1)
+            show_banner
+            loading_animation
+            echo "Launching Pterodactyl Panel installer..."
+            sleep 1
+            sudo bash <(curl -s https://raw.githubusercontent.com/guldkage/Pterodactyl-Installer/main/installer.sh)
+            read -p "Press enter to return to menu..."
+            ;;
+        2)
+            show_banner
+            loading_animation
+            echo "Launching Pterodactyl Wings installer..."
+            sleep 1
+            sudo bash <(curl -s https://raw.githubusercontent.com/guldkage/Pterodactyl-Installer/main/installer.sh)
+            read -p "Press enter to return to menu..."
+            ;;
+        3)
+            show_banner
+            loading_animation
+            echo "Installing Cloudflare..."
+            sudo mkdir -p --mode=0755 /usr/share/keyrings >/dev/null 2>&1
+            curl -fsSL https://pkg.cloudflare.com/cloudflare-public-v2.gpg | sudo tee /usr/share/keyrings/cloudflare-public-v2.gpg >/dev/null 2>&1
+            echo 'deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list >/dev/null 2>&1
+            sudo apt-get update >/dev/null 2>&1 && sudo apt-get install -y cloudflared >/dev/null 2>&1
+            echo "Cloudflare installed!"
+            read -p "Press enter to return to menu..."
+            ;;
+        4)
+            show_banner
+            loading_animation
+            echo "Installing Nebula Theme..."
+            git clone https://github.com/username5642/nebula.git nebula >/dev/null 2>&1
+            cd nebula || exit
+            ./install.sh >/dev/null 2>&1 || echo "Run your Nebula install steps here"
+            cd ..
+            echo "Nebula Theme installed!"
+            read -p "Press enter to return to menu..."
+            ;;
+        0)
+            echo "Exiting..."
+            exit 0
+            ;;
+        *)
+            echo "Invalid option."
+            sleep 1
+            ;;
+    esac
 done
-
-# Remove lib.sh, so next time the script is run the, newest version is downloaded.
-rm -rf /tmp/lib.sh
